version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  deploy:
    docker:
      - image: cimg/node:16.15.0
    environment:
      AWS_REGION: eu-west-2
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - aws-s3/sync:
          from: build
          to: s3://portfolio-website-stephen-kinnaird/
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
workflows:
  version: 2.1
  build:
    jobs:
      - deploy:
          # requires:
          #   - test
          filters:
            branches:
              only: main